version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3006:3006"
    networks:
      default:
        aliases:
          - mysql.dev
    environment:
      MYSQL_ROOT_PASSWORD: root-pwd
      MYSQL_DATABASE: task-manager

  task-manager:
    build:
      context: ./
    ports:
      - "3000:3000"
